### ISSUE TITLE
百度网盘上的那个TDB药品疾病知识库是不是有点不太对？

### ISSUE THREAD

**Issue by 2464599943** [YeYzheng/KGQA-Based-On-medicine#1]

**Comment by YeYzheng** [comment]
哪

**Comment by seraphcui** [comment]
数据
TDB药品疾病知识库
https://pan.baidu.com/s/1V7yqs4HKcQYJqDznf2MbSA
这里的网盘链接是不是不太对？

**Comment by plb31949** [comment]
我打开看不到文件，有可用的链接么

**Comment by 2464599943** [comment]
我调试过了，可以使用，谢谢参考，我收获很大😄😄😄



---原始邮件---
发件人: "plb31949"<notifications@github.com&gt;
发送时间: 2020年3月16日(周一) 下午4:20
收件人: "YeYzheng/KGQA-Based-On-medicine"<KGQA-Based-On-medicine@noreply.github.com&gt;;
抄送: "2464599943"<2464599943@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [YeYzheng/KGQA-Based-On-medicine] 百度网盘上的那个TDB药品疾病知识库是不是有点不太对？ (#1)




 
我打开看不到文件，有可用的链接么

**Comment by plb31949** [comment]
可以帮忙提供可用的TDB数据或者链接么
